### ISSUE TITLE
some remaining letters

### ISSUE THREAD

**Issue by armantaherian** [ImanMh/persianRex#4]
**٪**

```
۱۰% => is not persian
۱۰٪ => is persian
```

**?**

```
? => is not persian
؟ => is persian
```

**ـ**

```
سلــــام => is not persian?
```

And what about “﷼”, “«”, and “»”? I think all of them are persian letter.

**Comment by ImanMh** [comment]
Thanks for reporting these letters, I'm working on making a new category called punctuationMarks containing all of these:

```
۱- نقطه: .

۲- ویرگول: ،

۳- دو نقطه: :

۴- سؤال: ؟

۵- علامت عاطفه: !

۶- گیومه: « »

۷- نقطه ویرگول: ؛

۸- خطّ فاصله: -

۹- سه نقطه: ...

۱۰- قلاب: [ ]

۱۱- کمانک: ( )

۱۲- ممیّز: /

۱۳- تساوی: =
```

`﷼` is a rare case only containing on windows keyboard layout. But since it's the most popular OS in Iran, I'm really thinking about adding this as well, but I'm not sure if I do it in the next version (if I don't I will definitly add a way to fix the issue via configurations). 

I'm a little bit concern about `ـ` . it's not a punctuation mark or a Persian letter but I agree with you. It must be included some how. Any suggestions?

**Comment by ImanMh** [comment]
Since adding punctuation marks like  `%` can effect English inputs as well, I decided to add only `،؟«»؛` to the punctuation marks of the library.
Thanks for your positive and helpful feedback. Please feel free to open up other issues and I will try to fix it asap.

**Comment by ImanMh** [comment]
by the way If you or your company want to appear in sponsors area please send me your logo and tell me to add it.
